spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Santhosh@18
    url: jdbc:mysql://localhost:3306/mydb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create